#
# MCP Server Docker Compose Orchestration
#
# This file defines all MCP servers and supporting containers for the Pentest-Agent architecture.
# Each service is documented with its purpose and the Dockerfile it uses.
#
# Services:
#   - kali:      Kali Linux container with proper MCP server for shell/pentest tools (kali.Dockerfile)
#   - websearch: Web search MCP server (websearch.Dockerfile)
#   - rag:       RAG knowledge base MCP server (rag.Dockerfile)
#   - playwright: Playwright browser automation (playwright.Dockerfile)
#
# Container Naming Convention:
#   - MCP servers: mcp-{service} (e.g., mcp-kali, mcp-zap, mcp-websearch)
#   - Non-MCP services: {prefix}-{service} (e.g., pentest-playwright)
#
# MCP Protocol:
#   - All MCP servers use stdio communication (no HTTP ports needed)
#   - Proper MCP protocol with tool schemas and validation
#   - Interoperable with any MCP-compliant client
#
services:
  playwright:
    build:
      context: .
      dockerfile: playwright.Dockerfile  # Browser automation (not MCP)
    container_name: pentest-playwright
    working_dir: /app
    tty: true
    volumes:
      - ../outputs:/app/outputs

  kali:
    build:
      context: .
      dockerfile: kali.Dockerfile  # Kali MCP server (shell/pentest tools)
    container_name: mcp-kali
    networks:
      - mcp-network
    restart: unless-stopped

  websearch:
    build:
      context: .
      dockerfile: websearch.Dockerfile  # Web search MCP server
    container_name: mcp-websearch
    networks:
      - mcp-network
    restart: unless-stopped

  rag:
    build:
      context: .
      dockerfile: rag.Dockerfile  # RAG knowledge base MCP server
    container_name: mcp-rag
    networks:
      - mcp-network
    restart: unless-stopped

networks:
  mcp-network:
    driver: bridge 